name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: build with logs
        run: |
          mkdir ${{ runner.tmp }}/build_logs
          echo '123' > ${{ runner.tmp }}/build_logs/log.txt
      - name: upload logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Build failure logs
          path: ${{ runner.temp }}/build_logs