name: essential-feature-04-download-file
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      - run: ls ./
      
      