name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'
      - run: echo "the job was automatically triggered by a ${{ github.event_name }} event."